import React from "react"
import Head from "next/head"
import NavBar from "../components/navigationbar"
import Footer from "../components/footer"




export default function gallery(){
    return(
        <div>
            <Head>
                <title>Clarity By James Henderson Hairdressing</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
            </Head>
            <NavBar/>
            
        
        
        




        
        
        
        
        
        
        
        </div>
    )
}