import React from "react"
import Head from "next/head"
import Image from "next/image"
import ImageCarousel from "../components/ImageCarousel"
import Navbar from "../components/navigationbar"
import Footer from "../components/footer"



let testImages = [
    {src: "/../public/Logos/browsbybec.jpg"},
    {src: "/../public/Logos/letsgetlashed.jpg"},
    {src: "/../public/Logos/youandeye.jpg"}
]


export default function otherbusinesses(){
    return(
        <div>
            <Head>
				<title>Clarity By James Henderson Hairdressing</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
            <Navbar/>
            <div className="flex justify-center items-center pt-32 animate-fade-in-down">
                <h1 className="font-italianno text-4xl md:text-7xl">Clarity Beauty Lounge</h1>
            </div>
            <div className="justify-center items-center animate-fade-in-down align-center p-7">
                <p className="text-justify md:px-10 font-gayathri">
                The Clarity beauty lounge has been designed to take you to another place. It’s peaceful atmosphere and visionary design will have you relaxed within minutes of arriving. The beautiful large windows open up the space and have you feeling apart of the big wide world. The stunning glow of the natural sunlight instantly has you at the gateway to heaven. The Clarity beauty lounge is comprised of Adelaide beauty businesses that all take beauty to the next level. Each business has been hand picked by James to ensure the highest quality of work is being produced. These businesses not only take the upmost pride in their profession but also have a passion for ensuring all of their clients are looked after with heartfelt care. Please take a moment to become familiar with these local Adelaide businesses that have so lovingly been selected to have residency at the Clarity beauty lounge.
                </p>
            </div>
                <div class=" rounded-xl md:px-24 flex flex-col justify-center items-center animate-fade-in-down">
                    <div class="md:flex">
                        <div className="md:w-[99rem] relative">
                            <Image src="/../public/Logos/letsgetlashed.jpg" layout="fill" className="rounded"/>
                        </div>
                        <div class="p-8">
                            <h3 class="font-italianno text-4xl md:text-6xl mb-5">Let's Get Lashed</h3>
                            <p className="text-justify">
                                Khiara is the face behind Let’s Get Lashed.  She has owned her own lash and brow business for 5 years and still has the same passion as day 1. She specialises in all lash extension services including classics, hybrids and volumes, you name it she can do it. She also has you covered for your lash lifts and tints.
                                Stand out with beautiful brows ~ Khiara is also skilled in brow waxing and takes pleasure in creating the perfect shape to suit you. With laminations being a hot trend she can give you the bold brows you always dreamed of and tops it of with a hybrid tint giving you the perfect definition. To book in with Khiara click on the link in her Instagram bio @letsgetlasheddd.  
                            </p>
                            <button class="mt-5 rounded-lg px-4 py-2 bg-clarityGold text-blue-50 shadow hover:shadow-xl duration-300">
                                Instagram
                            </button>
                        </div>
                    </div>
                </div>
                <div class=" flex flex-col justify-center items-center animate-fade-in-down md:mt-32 md:px-24">
                    <div class="md:flex">
                        <div className="md:w-[96.9rem] relative">
                            <Image src="/../public/Logos/youandeye.jpg" layout="fill" className="rounded"/>
                        </div>
                        <div class="p-8">
                            <h3 class="font-italianno text-4xl md:text-6xl mb-5">You and Eye Beauty</h3>
                            <p className="text-justify">
                                With years of experience under her belt, Tiffany is well experienced and trained to help all the lovely ladies of adelaide feel the best they can in their own skin. 
                                Passionate about health, beauty and helping all women feel beautiful, Tiffany has hand-chosen all her lash products personally, and uses only the highest quality products possible. 
                                Having run her own successful lash business for years, Tiffany knows the importance of offering after-hour services - which she is happy to offer to all you gorgeous girls.
                                We can’t wait for you all to meet Tiffany; and to book in for your next set of gorgeous lash extensions with one of the best in the industry! She will be working at Clarity on Thursdays and Saturdays and is now taking booking for March the 3rd and the 5th. 
                                Head over to her page @youandeye.beauty_ for a follow and and have a look at her amazing work. To make an appointment please DM @youandeye.beauty_ .
                            </p>
                            <button class="mt-5 rounded-lg px-4 py-2 bg-clarityGold text-blue-50 shadow hover:shadow-xl duration-300">
                                Instagram
                            </button>
                        </div>
                    </div>
                </div>
                <div class=" flex flex-col justify-center items-center animate-fade-in-down  md:mt-32 md:px-24">
                    <div class="md:flex">
                        <div className="md:w-[96.9rem] relative">
                            <Image src="/../public/Logos/youandeye.jpg" layout="fill" className="rounded"/>
                        </div>
                        <div class="p-8">
                            <h3 class="font-italianno text-4xl md:text-6xl mb-5">You and Eye Beauty</h3>
                            <p className="text-justify">
                                With years of experience under her belt, Tiffany is well experienced and trained to help all the lovely ladies of adelaide feel the best they can in their own skin. 
                                Passionate about health, beauty and helping all women feel beautiful, Tiffany has hand-chosen all her lash products personally, and uses only the highest quality products possible. 
                                Having run her own successful lash business for years, Tiffany knows the importance of offering after-hour services - which she is happy to offer to all you gorgeous girls.
                                We can’t wait for you all to meet Tiffany; and to book in for your next set of gorgeous lash extensions with one of the best in the industry! She will be working at Clarity on Thursdays and Saturdays and is now taking booking for March the 3rd and the 5th. 
                                Head over to her page @youandeye.beauty_ for a follow and and have a look at her amazing work. To make an appointment please DM @youandeye.beauty_ .
                            </p>
                            <button class="mt-5 rounded-lg px-4 py-2 bg-clarityGold text-blue-50 shadow hover:shadow-xl duration-300">
                                Instagram
                            </button>
                            <ImageCarousel image={testImages} />
                        </div>
                    </div>
                </div>
                <Footer/>
            </div>
    )
}