import React from "react"
import Head from "next/head"
import Image from "next/image"
import Navbar from "../components/navigationbar"
import Footer from "../components/footer"


{/* Image path object array currently in progress but has to be put on hold for a little  */}
let testImages = [
    { src: "/../public/Logos/browsbybec.jpg" },
    { src: "/../public/Logos/letsgetlashed.jpg" },
    { src: "/../public/Logos/youandeye.jpg" }
]


export default function otherbusinesses() {
    return (
        <div>
            <Head>
                <title>Clarity By James Henderson Hairdressing</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Navbar />
            <section className="body-font">
                <div className="md:container px-5 py-24 mx-auto">
                    <div className="flex flex-col text-center w-full mb-20">
                        <h1 className="lg:text-5xl text-4xl font-medium title-font mb-4 text-gray-900 tracking-widest font-italianno">Clarity Beauty Lounge</h1>
                        <p className="lg:w-4/5 mx-auto leading-relaxed text-justify text-base font-gayathri">The Clarity beauty lounge has been designed to take you to another place. It’s peaceful atmosphere and visionary design will have you relaxed within minutes of arriving. The beautiful large windows open up the space and have you feeling apart of the big wide world. The stunning glow of the natural sunlight instantly has you at the gateway to heaven. The Clarity beauty lounge is comprised of Adelaide beauty businesses that all take beauty to the next level. Each business has been hand picked by James to ensure the highest quality of work is being produced. These businesses not only take the upmost pride in their profession but also have a passion for ensuring all of their clients are looked after with heartfelt care. Please take a moment to become familiar with these local Adelaide businesses that have so lovingly been selected to have residency at the Clarity beauty lounge.</p>
                    </div>
                    <div className="flex flex-wrap -m-4 grid-cols-1">
                        <div className="p-4 mb-20">
                            <div className="h-full flex sm:flex-row flex-col items-center sm:justify-start justify-center text-center sm:text-left">
                                <div className="flex-shrink-0 rounded-lg  object-cover object-center sm:mb-0 mb-4">
                                    <Image src="/../public/Logos/letsgetlashed.jpg" width={285} height={200} />
                                </div>
                                <div className="flex-grow sm:pl-8">
                                    <h2 className="title-font font-medium text-4xl text-gray-900 font-italianno">Let's Get Lashed</h2>
                                    <h3 className="mb-3 font-gayathri">Khiara - @letsgetlasheddd</h3>
                                    <p className="mb-4 text-justify font-gayathri">Khiara is the face behind Let’s Get Lashed.  She has owned her own lash and brow business for 5 years and still has the same passion as day 1. She specialises in all lash extension services including classNameics, hybrids and volumes, you name it she can do it. She also has you covered for your lash lifts and tints.
                                        Stand out with beautiful brows ~ Khiara is also skilled in brow waxing and takes pleasure in creating the perfect shape to suit you. With laminations being a hot trend she can give you the bold brows you always dreamed of and tops it of with a hybrid tint giving you the perfect definition. To book in with Khiara click on the link in her Instagram bio.</p>
                                </div>
                            </div>
                        </div>
                        <div className="p-4">
                            <div className="h-full flex sm:flex-row flex-col items-center sm:justify-start justify-center text-center sm:text-left">
                                <div className="flex-shrink-0 rounded-lg  object-cover object-center sm:mb-0 mb-4">
                                    <Image src="/../public/Logos/browsbybec.jpg" width={285} height={200} />
                                </div>
                                <div className="flex-grow sm:pl-8">
                                    <h2 className="title-font font-medium text-4xl text-gray-900 font-italianno">Brows by Bec</h2>
                                    <h3 className="mb-3 font-gayathri">Bec - @brows_bybec </h3>
                                    <p className="mb-4 text-justify font-gayathri">Brows by Bec offers Cosmetic Tattooing services. This includes the Ombré Brow technique, Feather touch Brows (Microblading) and the Combination Brow technique.
                                        Bec has been a Cosmetic eyebrow Tattoo specialist for almost 2.5 years now. She has a passion for all things beauty and loves transforming & enhancing brows. Bec takes pride in ensuring each set of brows
                                        is personalised for each person’s face shape and features through every appointment. She completes this through pre drawing each set of brows and engaging with her clientele to choose the perfect colour to match
                                        their brow hairs and facial features. Whether a natural enhancement or a bold brow is your preference, Bec can create a fabulous semi permanent set of brows! All bookings can be made via Instagram</p>
                                </div>
                            </div>
                        </div>
                        <div className="p-4">
                            <div className="h-full flex sm:flex-row flex-col items-center sm:justify-start justify-center text-center sm:text-left">
                            <div className="flex-shrink-0 rounded-lg  object-cover object-center sm:mb-0 mb-4">
                                    <Image src="/../public/Logos/youandeye.jpg" width={285} height={200} />
                                </div>
                                <div className="flex-grow sm:pl-8">
                                    <h2 className="title-font font-medium text-4xl text-gray-900 font-italianno">You and Eye Beauty</h2>
                                    <h3 className="mb-3 font-gayathri">Tiffany - @youandeye.beauty_</h3>
                                    <p className="mb-4 text-justify font-gayathri">With years of experience under her belt, Tiffany is well experienced and trained to help all the lovely ladies of adelaide feel the best they can in their own skin.
                                        Passionate about health, beauty and helping all women feel beautiful, Tiffany has hand-chosen all her lash products personally, and uses only the highest quality products possible.
                                        Having run her own successful lash business for years, Tiffany knows the importance of offering after-hour services - which she is happy to offer to all you gorgeous girls.
                                        We can’t wait for you all to meet Tiffany; and to book in for your next set of gorgeous lash extensions with one of the best in the industry! She will be working at Clarity on Thursdays and Saturdays and is now taking booking for March the 3rd and the 5th.
                                        Head over to her page @youandeye.beauty_ for a follow and and have a look at her amazing work. To make an appointment please DM</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <Footer />
        </div>
    )
}