import Head from "next/head"
import react from "react"
import Image from "next/image"
import Navbar from "../components/navigationbar"
import Footer from "../components/footer"
import Button from "../components/button"
import Cards from "../components/cards"
import Scissors from "../public/scissors.jpeg"


export default function pricing() {
    return(
        <div className="bg-offwhite">
            <Head>
				<title>Clarity By James Henderson Hairdressing</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
            <Navbar />
            <div className="flex justify-center items-center pt-40 animate-fade-in-down ">
                <h1 className="font-italianno text-4xl md:text-7xl">Services</h1>
            </div>
                <div>
                    <ul className="p-10 grid grid-cols-1 md:grid-cols-6 lg:grid-cols-3 xl:grid-cols-3 gap-5 animate-fade-in-down ">
                        <li className="block_overlay">
                            <h1 className="text-1xl md:text-5xl font-italianno text-center "> CUTS </h1>
                            <br></br>
                            <p className="font-gayathri"> Ladies cut and blow dry  <span className="float-right">$80</span>  <br/>
                                Dry cut / wash and cut <span className="float-right">$70</span> <br/>
                                Basic trim  <span className="float-right">$50</span> <br/>
                                Restyle cut <span className="float-right">$110</span><br/>
                            </p>
                        </li>
                        <li className="block_overlay">
                            <h1 className="text-1xl md:text-5xl font-italianno text-center"> COLOURING </h1>
                            <br></br>
                            <p className="font-gayathri"> Root tint  <span className="float-right">$75</span> <br/>
                                Tint short <span className="float-right">$85 </span><br/>
                                Tint medium <span className="float-right">$95</span><br/>
                                Tint long <span className="float-right">$105</span><br/>
                                Tint extra long <span className="float-right">$115</span><br/>
                                Bleach on scalp <span className="float-right">$130</span><br/>
                            </p>
                        </li>
                        <li className="block_overlay">
                            <Image className="rounded" src={Scissors} width={300} height={250}/ >
                            <h1> CUTTING </h1>
                            <p> adsjfkasdads</p>
                        </li>
                        <li className="block_overlay">
                            <Image className="rounded" src={Scissors} width={300} height={250}/ >
                            <h1> CUTTING </h1>
                            <p> adsjfkasdads</p>
                        </li>
                        <li className="block_overlay">
                            <Image className="rounded" src={Scissors} width={300} height={250}/ >
                            <h1> CUTTING </h1>
                            <p> adsjfkasdads</p>
                        </li>
                        <li className="block_overlay">
                            <Image className="rounded" src={Scissors} width={300} height={250}/ >
                            <h1> CUTTING </h1>
                            <p> adsjfkasdads</p>
                        </li>
                        <li className="block_overlay">
                            <Image className="rounded" src={Scissors} width={300} height={250}/ >
                            <h1> CUTTING </h1>
                            <p> adsjfkasdads</p>
                        </li>
                        <li className="block_overlay">
                            <Image className="rounded" src={Scissors} width={300} height={250}/ >
                            <h1> CUTTING </h1>
                            <p> adsjfkasdads</p>
                        </li>
                        <li className="block_overlay">
                            <Image className="rounded" src={Scissors} width={300} height={250}/ >
                            <h1> CUTTING </h1>
                            <p> adsjfkasdads</p>
                        </li>
                    </ul>
                </div>
                <Footer />
        </div>
    )
}