import Head from "next/head"
import react from "react"
import Navbar from "../components/navigationbar"
import Footer from "../components/footer"
import Button from "../components/button"

export default function pricing() {
    return(
        <div>
            <Head>
				<title>Clarity By James Henderson Hairdressing</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
			</Head>
            <Navbar />
            <div className="flex justify-center items-center pt-40">
                <h1>Pricing section</h1>
            </div>
        </div>
    )
}