import Head from "next/head"
import react from "react"
import Navbar from "../components/navigationbar"
import Footer from "../components/footer"
import Button from "../components/button"
import Cards from "../components/cards"

export default function pricing() {
    return(
        <div>
            <Head>
				<title>Clarity By James Henderson Hairdressing</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
            <Navbar />
            <div className="flex justify-center items-center pt-40">
                <h1>Pricing section</h1>
            </div>
                <div className="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-6 lg:grid-cols-3 xl:grid-cols-3 gap-5">
                    <Cards title="World" desc="this is a test of the props to see if they work"/>

                </div>
            </div>
    )
}